
module.exports =  [
    {
        id: "a6135646-7a2a-40a0-bce2-40da3f76f078",
        name: "Number",
        list_name: "Number",
        synonym: "Число",
        list_synonym: "Число", 
        table_name: "",
        class_name: "",
        database_type: "",
        is_md_type: false,
        has_length:false,
        has_fraction:false,
        order:0,
        field_type:true,
    },
    {
        id: "38a7b85c-acd0-4a3a-aa2b-02f685007f49",
        name: "String",
        list_name: "String",
        synonym: "Строка",
        list_synonym: "Строка",
        table_name: "",
        class_name: "",
        database_type: "",
        is_md_type: false,
        has_length:false,
        has_fraction:false,
        order:1,
        field_type:true,
    },
    {
        id: "19034973-d6a4-4dbf-b900-4eb9a78e405b",
        name: "Boolean",
        list_name: "Boolean",
        synonym: "Логический",
        list_synonym: "Логический",
        table_name: "",
        class_name: "",
        database_type: "",
        is_md_type: false,
        has_length:false,
        has_fraction:false, 
        order:2,
        field_type:true,
    },
    {
        id: "f41b5064-97a6-4ff3-b878-73747f0a8733",
        name: "Date",
        list_name: "Date",
        synonym: "Дата",
        list_synonym: "Дата",
        table_name: "",
        class_name: "",
        database_type: "",
        is_md_type: false,
        has_length:false,
        has_fraction:false, 
        order:2,
        field_type:true,
    },
    {
        id: "bb5fa9d9-17f0-4246-8470-a76977058cc2",
        name: "UUID",
        list_name: "UUID",
        synonym: "Уникальный идентификатор",
        list_synonym: "Уникальный идентификатор",
        table_name: "",
        class_name: "",
        database_type: "",
        is_md_type: false,
        has_length:false,
        has_fraction:false, 
        order:3,
        field_type:true,
    },
    {
        id: "414d13cc-913b-424d-81b5-e57f46e9d4f1",
        name: "Enumeration",
        list_name: "Enumerations",
        synonym: "Перечисление",
        list_synonym: "Перечисления",
        table_name: "md_enums",
        class_name: "MdEnum",
        database_type: "",
        is_md_type: true,
        has_length:false,
        has_fraction:false,
        order:9,
        field_type:true,
    },
    {
        id: "13274bca-5ab0-4c88-be70-9589763fc07f",
        name: "EnumerationItem",
        list_name: "EnumerationItemss",
        synonym: "Значение перечисления",
        list_synonym: "Значения перечиления",
        table_name: "md_enums_values",
        class_name: "MdEnumItem",
        database_type: "",
        is_md_type: true,
        has_length:false,
        has_fraction:false,
        order:10,
        field_type:false,
    },
    {
        id: "834cd9ad-9720-4fc5-aa09-cef6f7a895a0",
        name: "Catalogs",
        list_name: "Catalogs",
        synonym: "Справочник",
        list_synonym: "Справочники",
        table_name: "md_catalogs",
        class_name: "MdCatalog",
        database_type: "",
        is_md_type: true,
        has_length:false,
        has_fraction:false,
        order:11,
        field_type:true,
    },
    {
        id: "cc94220b-20f8-4a63-9f29-d02fe64ba918",
        name: "Documents",
        list_name: "Documents",
        synonym: "Документ",
        list_synonym: "Документы",
        table_name: "md_documents",
        class_name: "MdDocument",
        database_type: "",
        is_md_type: true,
        has_length:false,
        has_fraction:false,
        order:12,
        field_type:true,
    },
    {
        id: "0cf72dda-2547-4333-aec0-c852d2f3f235",
        name: "Tables",
        list_name: "Tables",
        synonym: "Таблица",
        list_synonym: "Таблицы",
        table_name: "md_tables",
        class_name: "MdTable",
        database_type: "",
        is_md_type: true,
        has_length:false,
        has_fraction:false,
        order:13,
        field_type:false,
    },
    {
        id: "8c474f75-b63a-4f3a-b624-f9a58cb7eeae",
        name: "Fields",
        list_name: "Fields",
        synonym: "Реквизит",
        list_synonym: "Реквизиты",
        table_name: "md_fields",
        class_name: "MdField",
        database_type: "",
        is_md_type: true,
        has_length:false,
        has_fraction:false,
        order:14,
        field_type:false,
    },
    {
        id: "370c9fb7-c2c8-4360-9863-6dc456460080",
        name: "WebForms",
        list_name: "WebForms",
        synonym: "ВебФорма",
        list_synonym: "ВебФормы",
        table_name: "md_webforms",
        class_name: "MdWebForm",
        database_type: "",
        is_md_type: true,
        has_length:false,
        has_fraction:false,
        order:15,
        field_type:false,
    },
    {
        id: "60a34539-5b85-4d96-b619-cefc7b6b894b",
        name: "Users",
        list_name: "Users",
        synonym: "Пользователь",
        list_synonym: "Пользователи",
        table_name: "md_users",
        class_name: "MdUser",
        database_type: "",
        is_md_type: true,
        has_length:false,
        has_fraction:false,
        order:16,
        field_type:false,
    },
    {
        id: "1ba5d068-38a7-44e5-82b8-d51e680a6cb1",
        name: "Domains",
        list_name: "Domains",
        synonym: "Домен",
        list_synonym: "Домены",
        table_name: "md_domains",
        class_name: "MdDomain",
        database_type: "",
        is_md_type: true,
        has_length:false,
        has_fraction:false,
        order:17,
        field_type:false,
    },
    {
        id: "b2aa362b-5872-411a-9cd8-fc65428e54eb",
        name: "Reports",
        list_name: "Reports",
        synonym: "Отчет",
        list_synonym: "Отчеты",
        table_name: "md_reports",
        class_name: "MdReport",
        database_type: "",
        is_md_type: true,
        has_length:false,
        has_fraction:false,
        order:18,
        field_type:false,
    },
    {
        id: "273c017b-b7d9-49a2-ac51-e0f2d6f0f75c",
        name: "Subsystem",
        list_name: "Subsystems",
        synonym: "Подсистема",
        list_synonym: "Подсистемы",
        table_name: "md_subsystems",
        class_name: "MdSubsystem",
        database_type: "",
        is_md_type: true,
        has_length:false,
        has_fraction:false,
        order:19,
        field_type:false,
    },
    {
        id: "6929b322-5a6a-4cc7-b002-d80460776ec2",
        name: "MenuItem",
        list_name: "MenuItems",
        synonym: "Элемент меню",
        list_synonym: "Элементы меню",
        table_name: "md_menu_items",
        class_name: "MdMenuItem",
        database_type: "",
        is_md_type: true,
        has_length:false,
        has_fraction:false,
        order:20,
        field_type:false,
    },
];

